name: Golang CI Lint

on:
  pull_request:

concurrency:
  group: golangci-lint
  cancel-in-progress: true

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/vbyazilim
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=5m
